version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - ./backend/.env      # <--- antes era ./.env
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health',res=>{process.exit(res.statusCode===200?0:1)}).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 5



  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      # ❌ No fijes VITE_API_URL en prod; deja que el código use mismo origen
      # args:
      #   VITE_API_URL: ""
    ports:
      - "8080:80"
    depends_on:
      - api
    # ⬇️ monta nuestra configuración de Nginx con el proxy /api
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
